### ISSUE TITLE
Cloudflared daemon not woking with Named Argo Tunnel.

### ISSUE THREAD

**Issue by jjpinom** [BH4EHN/openwrt-cloudflared#1]
Please update de release to the most recent version.

**Comment by BH4EHN** [comment]
there's too many arch to build, you can build for your own use the sdk at the bottom of OpenWRT image download page. 
for example, the `openwrt-sdk-19.07.7-mvebu-cortexa9_gcc-7.5.0_musl_eabi.Linux-x86_64.tar.xz` in `https://downloads.openwrt.org/releases/19.07.7/targets/mvebu/cortexa9/`

**Comment by mickeydarrenlau** [comment]
How to compile

**Comment by BH4EHN** [comment]
@mickeydarrenlau please read https://github.com/BH4EHN/openwrt-cloudflared/blob/master/README.md and https://openwrt.org/docs/guide-developer/single.package and https://openwrt.org/docs/guide-developer/using_the_sdk
